/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HMS;

import Login.Login;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import java.awt.print.PrinterException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Silvia Chinwendu
 */
public class HMS extends javax.swing.JFrame {
private JFrame frame; 
    /**
     * Creates new form HMS
     */
    public HMS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnDoctor = new javax.swing.JButton();
        btnGP = new javax.swing.JButton();
        btnPatient = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jbtnPrescription = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnLogin1 = new javax.swing.JButton();
        jbtnPrint = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtPrescription = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcmbNameTablets = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jtxtFurtherInformation = new javax.swing.JTextField();
        jtxtRef = new javax.swing.JTextField();
        jtxtDose = new javax.swing.JTextField();
        jtxtLot = new javax.swing.JTextField();
        jtxtNumberTablets = new javax.swing.JTextField();
        jtxtExpDate = new javax.swing.JTextField();
        jtxtIssuedDate = new javax.swing.JTextField();
        jtxtPossibleSideEffects = new javax.swing.JTextField();
        jtxtDailyDose = new javax.swing.JTextField();
        jtxtPatientAddress = new javax.swing.JTextField();
        jtxtStorageAdvice = new javax.swing.JTextField();
        jtxtDrivingUsingMachines = new javax.swing.JTextField();
        jtxtHowtoUseMedication = new javax.swing.JTextField();
        jtxtPatientID = new javax.swing.JTextField();
        jtxtDoctorNHSNo1 = new javax.swing.JTextField();
        jtxtPatientName = new javax.swing.JTextField();
        jtxtDOB = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 51));
        setMinimumSize(new java.awt.Dimension(1400, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 255, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 51), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 110, 30));

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 110, 30));

        btnDoctor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDoctor.setText("Doctor");
        btnDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctorActionPerformed(evt);
            }
        });
        jPanel1.add(btnDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 130, 30));

        btnGP.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnGP.setText("GP Appointment");
        btnGP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGPActionPerformed(evt);
            }
        });
        jPanel1.add(btnGP, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 130, 30));

        btnPatient.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnPatient.setText("Patient");
        btnPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientActionPerformed(evt);
            }
        });
        jPanel1.add(btnPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 120, 30));

        btnReset.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel1.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 130, 30));

        jbtnPrescription.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtnPrescription.setText("Prescription");
        jbtnPrescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrescriptionActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnPrescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 150, 30));

        btnExit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 10, 110, 30));

        btnLogin1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnLogin1.setText("Login");
        btnLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogin1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, 170, 30));

        jbtnPrint.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtnPrint.setText("Print");
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 10, 160, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name of Tablets", "Reference No", "Dose (mg)", "Number of Tablets", "LOT", "Issued Date", "Expiry Date", "Daily Dose", "Possible Side Effects", "Further Information", "Storage Advice", "Title 1Driving and Using Machine", "How to Use Medication", "Patient ID", "NHS Number", "Patient Name", "Date of Birth", "Ptient Address"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 1090, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, 1340, 50));

        jPanel2.setBackground(new java.awt.Color(51, 255, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 51), 3));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtPrescription.setColumns(20);
        jtxtPrescription.setRows(5);
        jScrollPane1.setViewportView(jtxtPrescription);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 10, 310, 530));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 100, 320, 550));

        jPanel3.setBackground(new java.awt.Color(51, 255, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 51), 3));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setText("Patient Prescription");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, -1, 60));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 1020, 60));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        jLabel1.setText("Hospital Management Systems");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1340, 80));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Reference No.:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jcmbNameTablets.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcmbNameTablets.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Make a Selection", "Paracetamol", "Ampiclox", "Armatem", "Diebetico" }));
        jcmbNameTablets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbNameTabletsActionPerformed(evt);
            }
        });
        getContentPane().add(jcmbNameTablets, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Name of Tablets:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Number of Tablets:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Dose (mg):");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Issued Date:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("LOT:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Possible Side Effects");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Exp Date:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Daily Dose:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Patient Address:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 600, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Date of Birth:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 550, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Patient Name:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 500, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("NHS Number:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 460, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Patient ID:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, 100, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("How to Use Medication:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("Driving and Using Machines:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 260, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("Storage Advice:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("Further Information:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, -1, 20));

        jtxtFurtherInformation.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtFurtherInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFurtherInformationActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtFurtherInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 180, 190, 30));

        jtxtRef.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtRefActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtRef, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 190, 30));

        jtxtDose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtDose, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 190, 30));

        jtxtLot.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtLot, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 190, -1));

        jtxtNumberTablets.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtNumberTablets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNumberTabletsActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtNumberTablets, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 190, -1));

        jtxtExpDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtExpDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, 190, 30));

        jtxtIssuedDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtIssuedDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, 190, 30));

        jtxtPossibleSideEffects.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtPossibleSideEffects, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 600, 190, 30));

        jtxtDailyDose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtDailyDose, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 550, 190, 30));

        jtxtPatientAddress.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtPatientAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 600, 190, 30));

        jtxtStorageAdvice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtStorageAdvice, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 230, 190, 30));

        jtxtDrivingUsingMachines.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtDrivingUsingMachines, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 300, 190, 30));

        jtxtHowtoUseMedication.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtHowtoUseMedication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtHowtoUseMedicationActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtHowtoUseMedication, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 350, 190, -1));

        jtxtPatientID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtPatientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 400, 190, -1));

        jtxtDoctorNHSNo1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtDoctorNHSNo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 450, 190, 30));

        jtxtPatientName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtPatientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPatientNameActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 500, 190, 30));

        jtxtDOB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtDOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDOBActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 550, 190, 30));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Number of Tablets", "Reference No", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12", "Title 13", "Title 14", "Title 15", "Title 16", "Title 17", "Title 18"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 710, 1320, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcmbNameTabletsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbNameTabletsActionPerformed
        // TODO add your handling code here:
        if (jcmbNameTablets.getSelectedItem().equals("Paracetamol"))
        {
            jtxtRef.setText("Para766887");
            jtxtDose.setText("2");
            jtxtNumberTablets.setText("30");
            jtxtLot.setText("54567567");
            jtxtIssuedDate.setText("06/05/2019");
            jtxtExpDate.setText("04/09/2023");
            jtxtDailyDose.setText("4");
            
            jtxtPossibleSideEffects.setText("Bleeding");
            jtxtFurtherInformation.setText("Place Dispensary");
            jtxtStorageAdvice.setText("Less than 20 degrees Celsuis");
            jtxtDrivingUsingMachines.setText("No");
            jtxtHowtoUseMedication.setText("Use water, No Alcohol");
            jtxtPatientID.setText("P6567565");
            jtxtDoctorNHSNo1.setText("67565");   
            
        }
            else if (jcmbNameTablets.getSelectedItem().equals("Ampiclox"))
            {
                jtxtRef.setText("Ampi27637");
                jtxtDose.setText("3");
                jtxtNumberTablets.setText("24");
                jtxtLot.setText("87876867");
                jtxtIssuedDate.setText("07/08/2019");
                jtxtExpDate.setText("05/09/2023");
                jtxtDailyDose.setText("2");
                
                jtxtPossibleSideEffects.setText("Nausea");
                jtxtFurtherInformation.setText("Place Dispensary");
                jtxtStorageAdvice.setText("Less than 20 degrees Celsuis");
                jtxtDrivingUsingMachines.setText("No");
                jtxtHowtoUseMedication.setText("Use water, No Alcohol");
                jtxtPatientID.setText("P56574");
                jtxtDoctorNHSNo1.setText("75789"); 
        }
        else if (jcmbNameTablets.getSelectedItem().equals("Armatem"))
            {
                jtxtRef.setText("Arma2435");
                jtxtDose.setText("1");
                jtxtNumberTablets.setText("16");
                jtxtLot.setText("6576862");
                jtxtIssuedDate.setText("07/08/2019");
                jtxtExpDate.setText("05/09/2023");
                jtxtDailyDose.setText("3");
                
                jtxtPossibleSideEffects.setText("Headache");
                jtxtFurtherInformation.setText("Place Dispensary");
                jtxtStorageAdvice.setText("Store out of Children's reach");
                jtxtDrivingUsingMachines.setText("No");
                jtxtHowtoUseMedication.setText("Use water, No Alcohol");
                jtxtPatientID.setText("P45435");
                jtxtDoctorNHSNo1.setText("75789");  
        }
        else if (jcmbNameTablets.getSelectedItem().equals("Diebetico"))
            {
                jtxtRef.setText("Die89867");
                jtxtDose.setText("2");
                jtxtNumberTablets.setText("10");
                jtxtLot.setText("6565644");
                jtxtIssuedDate.setText("07/08/2019");
                jtxtExpDate.setText("05/09/2023");
                jtxtDailyDose.setText("6");
                
                jtxtPossibleSideEffects.setText("Dizziness");
                jtxtFurtherInformation.setText("Ability to drive may be affected ");
                jtxtStorageAdvice.setText("No Special Storage");
                jtxtDrivingUsingMachines.setText("No");
                jtxtHowtoUseMedication.setText("Use water, No Alcohol");
                jtxtPatientID.setText("P86768");
                jtxtDoctorNHSNo1.setText("75789");  
        }
        else if (jcmbNameTablets.getSelectedItem().equals("Make a Selection"))
            {
                jtxtRef.setText("");
                jtxtDose.setText("");
                jtxtNumberTablets.setText("");
                jtxtLot.setText("");
                jtxtIssuedDate.setText("");
                jtxtExpDate.setText("");
                jtxtDailyDose.setText("");
                
                jtxtPossibleSideEffects.setText("");
                jtxtFurtherInformation.setText("");
                jtxtStorageAdvice.setText("");
                jtxtDrivingUsingMachines.setText("");
                jtxtHowtoUseMedication.setText("");
                jtxtPatientID.setText("");
                jtxtDoctorNHSNo1.setText("");  
        }
    }//GEN-LAST:event_jcmbNameTabletsActionPerformed

    private void jtxtNumberTabletsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNumberTabletsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNumberTabletsActionPerformed

    private void jtxtHowtoUseMedicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtHowtoUseMedicationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtHowtoUseMedicationActionPerformed

    private void jtxtRefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtRefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtRefActionPerformed

    private void jtxtDOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDOBActionPerformed

    private void jtxtFurtherInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFurtherInformationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFurtherInformationActionPerformed

    private void btnGPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGPActionPerformed
        // TODO add your handling code here:
        Login iLogin  = new Login();
        iLogin.setVisible(true);
    }//GEN-LAST:event_btnGPActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        jtxtRef.setText("");
        jtxtDose.setText("");
        jtxtNumberTablets.setText("");
        jtxtLot.setText("");
        jtxtIssuedDate.setText("");
        jtxtExpDate.setText("");
        jtxtDailyDose.setText("");

        jtxtPossibleSideEffects.setText("");
        jtxtFurtherInformation.setText("");
        jtxtStorageAdvice.setText("");
        jtxtDrivingUsingMachines.setText("");
        jtxtHowtoUseMedication.setText("");
        jtxtPatientID.setText("");
        jtxtDoctorNHSNo1.setText("");
        jcmbNameTablets.getModel().setSelectedItem("Make a Selection");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        if (jTable2.getSelectedRow () ==-1) {
            if (jTable2.getRowCount()==0) {
                
                JOptionPane.showMessageDialog(null, "No data to delete", "Hospital management Systems",
                        JOptionPane.OK_CANCEL_OPTION );
            }else {
                JOptionPane.showMessageDialog(null, "Select a row to delete", "Hospital management Systems",
                        JOptionPane.OK_CANCEL_OPTION );
            }
        }else {
            model.removeRow(jTable2.getSelectedRow());
        }
         
    }//GEN-LAST:event_btnDeleteActionPerformed
 
    private void btnDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorActionPerformed
        // TODO add your handling code here:
        Login iLogin  = new Login();
        iLogin.setVisible(true);
    }//GEN-LAST:event_btnDoctorActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        frame = new JFrame();
        if (JOptionPane.showConfirmDialog(frame, "Confirm you have saved your work, before you exit", "Hospital Management Systems",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
        // TODO add your handling code here:
        try {
            jtxtPrescription.print();   
        }catch (PrinterException ex){
            Logger.getLogger(HMS.class.getName()).log(Level.SEVERE, null, ex);
        }
         
    }//GEN-LAST:event_jbtnPrintActionPerformed

    private void jtxtPatientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPatientNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPatientNameActionPerformed

    private void jbtnPrescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrescriptionActionPerformed
        // TODO add your handling code here:
        String Qty1 = (jtxtRef.getText());
        String Qty2 = (jtxtDose.getText());
        String Qty3 = (jtxtNumberTablets.getText());
        String Qty4 = (jtxtLot.getText());
        String Qty5 = (jtxtDailyDose.getText());
        String Qty6 = (jtxtPossibleSideEffects.getText());
        String Qty7 = (jtxtFurtherInformation.getText());
        String Qty8 = (jtxtHowtoUseMedication.getText());
        String Qty9 = (jtxtPatientID.getText());
        String Qty10 = (jtxtPatientName.getText());
        String Qty11 = (jtxtDOB.getText());
        String Qty12 = (jtxtPatientAddress.getText());
        String Qty13 = "";
        
        if (jcmbNameTablets.getSelectedItem().equals("Paracetamol"))
        {
            Qty13 = "Paracetamol";
        }
         else if (jcmbNameTablets.getSelectedItem().equals("Ampiclox"))
        {
            Qty13 = "Ampiclox";
        }
         else if (jcmbNameTablets.getSelectedItem().equals("Armatem"))
        {
            Qty13 = "Armatem";
        }
         else if (jcmbNameTablets.getSelectedItem().equals("Diebetico"))
        {
            Qty13 = "Diebetico";
        }
          
        
        
        jtxtPrescription.setText("");
        jtxtPrescription.append("\t\n\tHospital Management Systems\n"
        +"\nPatient Name:\t\t" + Qty10
        +"\nDate of Birth: \t\t" + Qty11
        +"\nPatient Address:\t" + Qty12
        +"\nPrescription:\t\t" + Qty13
        +"\nReference No:\t\t" + Qty1
        +"\nDose (mg):\t\t" + Qty2
        +"\nNumber of Tablets:\t" + Qty3
        +"\nLOT:\t\t" + Qty4
        +"\nDaily Dose:\t\t" + Qty5
        +"\nPossible Side Effects:\t" + Qty6
        +"\nFurther Information:\t" + Qty7
        +"\nHow to Use Medication:\t" + Qty8
        +"\nPatient ID:\t\t" + Qty9
        +"\n\n\tPatient Instruction: "
                + "\nWe have introduced a free text confirmation\n\t" 
                + "\n----TEXT REMINDERS FOR APPOINTMENT----" );
      
    }//GEN-LAST:event_jbtnPrescriptionActionPerformed

    private void btnLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogin1ActionPerformed
        // TODO add your handling code here:
        Login iLogin  = new Login();
        iLogin.setVisible(true);
        
    }//GEN-LAST:event_btnLogin1ActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[] {jcmbNameTablets.getSelectedItem().toString(),
        jtxtRef.getText(), jtxtNumberTablets.getText(), jtxtLot.getText(), 
        jtxtIssuedDate.getText(), jtxtExpDate.getText(), jtxtDailyDose.getText(),
        jtxtPossibleSideEffects.getText(), jtxtDrivingUsingMachines.getText(),
        jtxtHowtoUseMedication.getText(), jtxtPatientID.getText(), jtxtDoctorNHSNo1.getText(),
        jtxtPatientName.getText(), jtxtDOB.getText(), jtxtPatientAddress.getText(), });
          
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientActionPerformed
        // TODO add your handling code here:
        Login iLogin  = new Login();
        iLogin.setVisible(true);
    }//GEN-LAST:event_btnPatientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HMS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDoctor;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnGP;
    private javax.swing.JButton btnLogin1;
    private javax.swing.JButton btnPatient;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton jbtnPrescription;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JComboBox<String> jcmbNameTablets;
    private javax.swing.JTextField jtxtDOB;
    private javax.swing.JTextField jtxtDailyDose;
    private javax.swing.JTextField jtxtDoctorNHSNo1;
    private javax.swing.JTextField jtxtDose;
    private javax.swing.JTextField jtxtDrivingUsingMachines;
    private javax.swing.JTextField jtxtExpDate;
    private javax.swing.JTextField jtxtFurtherInformation;
    private javax.swing.JTextField jtxtHowtoUseMedication;
    private javax.swing.JTextField jtxtIssuedDate;
    private javax.swing.JTextField jtxtLot;
    private javax.swing.JTextField jtxtNumberTablets;
    private javax.swing.JTextField jtxtPatientAddress;
    private javax.swing.JTextField jtxtPatientID;
    private javax.swing.JTextField jtxtPatientName;
    private javax.swing.JTextField jtxtPossibleSideEffects;
    private javax.swing.JTextArea jtxtPrescription;
    private javax.swing.JTextField jtxtRef;
    private javax.swing.JTextField jtxtStorageAdvice;
    // End of variables declaration//GEN-END:variables
}
